services:
  flutter:
    build: .
    container_name: flutter_dev
    ports:
      - "8080:8080"    # Flutter Web用のポートをマッピング
    volumes:
      - .:/app         # ソースコードの変更をリアルタイムに反映
    environment:
      - FLUTTER_WEB=true
    command: flutter run -d web-server --web-port 8080

  firebase:
    image: node:20
    container_name: firebase_emulator
    ports:
      - "4000:4000"    # Firebase Emulator UI
      - "8085:8085"    # Firestore Emulator
      - "9099:9099"    # Authentication Emulator
      - "9199:9199"    # Storage Emulator
    volumes:
      - ./firebase:/home/firebase/firebase  # firebase.json などの設定ファイルをマウント
    command: >
      sh -c "npm install -g firebase-tools && firebase emulators:start --project jp-takaakiu-nitaku"
    restart: always